// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/user-service/article.proto

package user_service

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	core "golang-microservices-boilerplate/proto/core"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Article Message ---
type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      string                 `protobuf:"bytes,7,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	PictureUrl    string                 `protobuf:"bytes,8,opt,name=picture_url,json=pictureUrl,proto3" json:"picture_url,omitempty"`
	Badge         string                 `protobuf:"bytes,9,opt,name=badge,proto3" json:"badge,omitempty"`
	FileIds       []string               `protobuf:"bytes,10,rep,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"` // Corrected example format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_proto_user_service_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_proto_user_service_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Article) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Article) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Article) GetPictureUrl() string {
	if x != nil {
		return x.PictureUrl
	}
	return ""
}

func (x *Article) GetBadge() string {
	if x != nil {
		return x.Badge
	}
	return ""
}

func (x *Article) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

// Create
type CreateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	PictureUrl    *string                `protobuf:"bytes,4,opt,name=picture_url,json=pictureUrl,proto3,oneof" json:"picture_url,omitempty"`
	Badge         *string                `protobuf:"bytes,5,opt,name=badge,proto3,oneof" json:"badge,omitempty"`
	FileIds       []string               `protobuf:"bytes,6,rep,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"` // Corrected example format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_proto_user_service_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_article_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateArticleRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreateArticleRequest) GetPictureUrl() string {
	if x != nil && x.PictureUrl != nil {
		return *x.PictureUrl
	}
	return ""
}

func (x *CreateArticleRequest) GetBadge() string {
	if x != nil && x.Badge != nil {
		return *x.Badge
	}
	return ""
}

func (x *CreateArticleRequest) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

type CreateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleResponse) Reset() {
	*x = CreateArticleResponse{}
	mi := &file_proto_user_service_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleResponse) ProtoMessage() {}

func (x *CreateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleResponse.ProtoReflect.Descriptor instead.
func (*CreateArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_article_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

// Get By ID
type GetArticleByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleByIDRequest) Reset() {
	*x = GetArticleByIDRequest{}
	mi := &file_proto_user_service_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleByIDRequest) ProtoMessage() {}

func (x *GetArticleByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleByIDRequest.ProtoReflect.Descriptor instead.
func (*GetArticleByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_article_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetArticleByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleByIDResponse) Reset() {
	*x = GetArticleByIDResponse{}
	mi := &file_proto_user_service_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleByIDResponse) ProtoMessage() {}

func (x *GetArticleByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleByIDResponse.ProtoReflect.Descriptor instead.
func (*GetArticleByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_article_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticleByIDResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

// List
type ListArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *core.FilterOptions    `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_proto_user_service_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_article_proto_rawDescGZIP(), []int{5}
}

func (x *ListArticlesRequest) GetOptions() *core.FilterOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListArticlesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Articles       []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	PaginationInfo *core.PaginationInfo   `protobuf:"bytes,2,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListArticlesResponse) Reset() {
	*x = ListArticlesResponse{}
	mi := &file_proto_user_service_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResponse) ProtoMessage() {}

func (x *ListArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_article_proto_rawDescGZIP(), []int{6}
}

func (x *ListArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *ListArticlesResponse) GetPaginationInfo() *core.PaginationInfo {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

// Update
type UpdateArticleRequest struct {
	state   protoimpl.MessageState  `protogen:"open.v1"`
	Id      string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title   *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	// author_id typically shouldn't be updated
	PictureUrl *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=picture_url,json=pictureUrl,proto3,oneof" json:"picture_url,omitempty"`
	Badge      *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=badge,proto3,oneof" json:"badge,omitempty"`
	// Use a specific message/field for managing file associations if needed, simple replacement shown here
	FileIds       *FileIDsUpdate `protobuf:"bytes,6,opt,name=file_ids,json=fileIds,proto3,oneof" json:"file_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_proto_user_service_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_article_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateArticleRequest) GetTitle() *wrapperspb.StringValue {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *UpdateArticleRequest) GetContent() *wrapperspb.StringValue {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UpdateArticleRequest) GetPictureUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.PictureUrl
	}
	return nil
}

func (x *UpdateArticleRequest) GetBadge() *wrapperspb.StringValue {
	if x != nil {
		return x.Badge
	}
	return nil
}

func (x *UpdateArticleRequest) GetFileIds() *FileIDsUpdate {
	if x != nil {
		return x.FileIds
	}
	return nil
}

// Helper message for updating repeated fields like file_ids
type FileIDsUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"` // Corrected example format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileIDsUpdate) Reset() {
	*x = FileIDsUpdate{}
	mi := &file_proto_user_service_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileIDsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileIDsUpdate) ProtoMessage() {}

func (x *FileIDsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileIDsUpdate.ProtoReflect.Descriptor instead.
func (*FileIDsUpdate) Descriptor() ([]byte, []int) {
	return file_proto_user_service_article_proto_rawDescGZIP(), []int{8}
}

func (x *FileIDsUpdate) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type UpdateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleResponse) Reset() {
	*x = UpdateArticleResponse{}
	mi := &file_proto_user_service_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleResponse) ProtoMessage() {}

func (x *UpdateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleResponse.ProtoReflect.Descriptor instead.
func (*UpdateArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_article_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

// Delete
type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HardDelete    bool                   `protobuf:"varint,2,opt,name=hard_delete,json=hardDelete,proto3" json:"hard_delete,omitempty"` // Corrected example format for bool
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_proto_user_service_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_article_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteArticleRequest) GetHardDelete() bool {
	if x != nil {
		return x.HardDelete
	}
	return false
}

var File_proto_user_service_article_proto protoreflect.FileDescriptor

const file_proto_user_service_article_proto_rawDesc = "" +
	"\n" +
	" proto/user-service/article.proto\x12\vuserservice\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17proto/core/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb1\b\n" +
	"\aArticle\x12=\n" +
	"\x02id\x18\x01 \x01(\tB-\x92A*2\x19Unique identifier (UUID).J\r\"uuid-string\"R\x02id\x12k\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB0\x92A-2\x13Creation timestamp.J\x16\"2023-10-27T10:00:00Z\"R\tcreatedAt\x12n\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB3\x92A02\x16Last update timestamp.J\x16\"2023-10-27T11:30:00Z\"R\tupdatedAt\x12\x82\x01\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampBB\x92A?2%Deletion timestamp (if soft-deleted).J\x16\"2023-10-28T09:15:00Z\"H\x00R\tdeletedAt\x88\x01\x01\x12:\n" +
	"\x05title\x18\x05 \x01(\tB$\x92A!2\x0eArticle title.J\x0f\"Article Title\"R\x05title\x12J\n" +
	"\acontent\x18\x06 \x01(\tB0\x92A-2\x10Article content.J\x19\"Article content here...\"R\acontent\x12P\n" +
	"\tauthor_id\x18\a \x01(\tB3\x92A02\x18Author's user ID (UUID).J\x14\"author-uuid-string\"R\bauthorId\x12p\n" +
	"\vpicture_url\x18\b \x01(\tBO\x92AL2)URL of the associated picture (optional).J\x1f\"https://example.com/image.jpg\"R\n" +
	"pictureUrl\x12P\n" +
	"\x05badge\x18\t \x01(\tB:\x92A72+Article badge ('common', 'good', 'danger').J\b\"common\"R\x05badge\x12d\n" +
	"\bfile_ids\x18\n" +
	" \x03(\tBI\x92AF2$List of associated file IDs (UUIDs).J\x1e[\"file-uuid-1\", \"file-uuid-2\"]R\afileIds:r\x92Ao\n" +
	"m*\aArticle2\x1dRepresents an article entity.\xd2\x01\x02id\xd2\x01\n" +
	"created_at\xd2\x01\n" +
	"updated_at\xd2\x01\x05title\xd2\x01\acontent\xd2\x01\tauthor_id\xd2\x01\x05badgeB\r\n" +
	"\v_deleted_at\"\x97\x05\n" +
	"\x14CreateArticleRequest\x12>\n" +
	"\x05title\x18\x01 \x01(\tB(\x92A%2\x0eArticle title.J\x13\"New Article Title\"R\x05title\x12O\n" +
	"\acontent\x18\x02 \x01(\tB5\x92A22\x10Article content.J\x1e\"Content for the new article.\"R\acontent\x12P\n" +
	"\tauthor_id\x18\x03 \x01(\tB3\x92A02\x18Author's user ID (UUID).J\x14\"author-uuid-string\"R\bauthorId\x12y\n" +
	"\vpicture_url\x18\x04 \x01(\tBS\x92AP2)URL of the associated picture (optional).J#\"https://example.com/new_image.jpg\"H\x00R\n" +
	"pictureUrl\x88\x01\x01\x12i\n" +
	"\x05badge\x18\x05 \x01(\tBN\x92AK2AArticle badge ('common', 'good', 'danger'). Defaults to 'common'.J\x06\"good\"H\x01R\x05badge\x88\x01\x01\x12_\n" +
	"\bfile_ids\x18\x06 \x03(\tBD\x92AA2.List of associated file IDs (UUIDs, optional).J\x0f[\"file-uuid-1\"]R\afileIds:;\x92A8\n" +
	"6*\x16Create Article Request\xd2\x01\x05title\xd2\x01\acontent\xd2\x01\tauthor_idB\x0e\n" +
	"\f_picture_urlB\b\n" +
	"\x06_badge\"g\n" +
	"\x15CreateArticleResponse\x12.\n" +
	"\aarticle\x18\x01 \x01(\v2\x14.userservice.ArticleR\aarticle:\x1e\x92A\x1b\n" +
	"\x19*\x17Create Article Response\"\x8c\x01\n" +
	"\x15GetArticleByIDRequest\x12L\n" +
	"\x02id\x18\x01 \x01(\tB<\x92A92 UUID of the article to retrieve.J\x15\"article-uuid-string\"R\x02id:%\x92A\"\n" +
	" *\x19Get Article By ID Request\xd2\x01\x02id\"k\n" +
	"\x16GetArticleByIDResponse\x12.\n" +
	"\aarticle\x18\x01 \x01(\v2\x14.userservice.ArticleR\aarticle:!\x92A\x1e\n" +
	"\x1c*\x1aGet Article By ID Response\"b\n" +
	"\x13ListArticlesRequest\x12-\n" +
	"\aoptions\x18\x01 \x01(\v2\x13.core.FilterOptionsR\aoptions:\x1c\x92A\x19\n" +
	"\x17*\x15List Articles Request\"\xa6\x01\n" +
	"\x14ListArticlesResponse\x120\n" +
	"\barticles\x18\x01 \x03(\v2\x14.userservice.ArticleR\barticles\x12=\n" +
	"\x0fpagination_info\x18\x02 \x01(\v2\x14.core.PaginationInfoR\x0epaginationInfo:\x1d\x92A\x1a\n" +
	"\x18*\x16List Articles Response\"\xd9\x05\n" +
	"\x14UpdateArticleRequest\x12J\n" +
	"\x02id\x18\x01 \x01(\tB:\x92A72\x1eUUID of the article to update.J\x15\"article-uuid-string\"R\x02id\x12Y\n" +
	"\x05title\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueB \x92A\x1d2\n" +
	"New title.J\x0f\"Updated Title\"H\x00R\x05title\x88\x01\x01\x12d\n" +
	"\acontent\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueB'\x92A$2\fNew content.J\x14\"Updated content...\"H\x01R\acontent\x88\x01\x01\x12\x82\x01\n" +
	"\vpicture_url\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueB>\x92A;2\x10New picture URL.J'\"https://example.com/updated_image.jpg\"H\x02R\n" +
	"pictureUrl\x88\x01\x01\x12o\n" +
	"\x05badge\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueB6\x92A32'New badge ('common', 'good', 'danger').J\b\"danger\"H\x03R\x05badge\x88\x01\x01\x12]\n" +
	"\bfile_ids\x18\x06 \x01(\v2\x1a.userservice.FileIDsUpdateB!\x92A\x1e2\x1cReplace associated file IDs.H\x04R\afileIds\x88\x01\x01:\"\x92A\x1f\n" +
	"\x1d*\x16Update Article Request\xd2\x01\x02idB\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_contentB\x0e\n" +
	"\f_picture_urlB\b\n" +
	"\x06_badgeB\v\n" +
	"\t_file_ids\"\x88\x01\n" +
	"\rFileIDsUpdate\x12_\n" +
	"\x03ids\x18\x01 \x03(\tBM\x92AJ2(New list of associated file IDs (UUIDs).J\x1e[\"file-uuid-3\", \"file-uuid-4\"]R\x03ids:\x16\x92A\x13\n" +
	"\x11*\x0fFile IDs Update\"g\n" +
	"\x15UpdateArticleResponse\x12.\n" +
	"\aarticle\x18\x01 \x01(\v2\x14.userservice.ArticleR\aarticle:\x1e\x92A\x1b\n" +
	"\x19*\x17Update Article Response\"\xd8\x01\n" +
	"\x14DeleteArticleRequest\x12J\n" +
	"\x02id\x18\x01 \x01(\tB:\x92A72\x1eUUID of the article to delete.J\x15\"article-uuid-string\"R\x02id\x12P\n" +
	"\vhard_delete\x18\x02 \x01(\bB/\x92A,2\x1cPerform hard delete if true.:\x05falseJ\x05falseR\n" +
	"hardDelete:\"\x92A\x1f\n" +
	"\x1d*\x16Delete Article Request\xd2\x01\x02id2\xeb\x05\n" +
	"\x0eArticleService\x12\x89\x01\n" +
	"\x06Create\x12!.userservice.CreateArticleRequest\x1a\".userservice.CreateArticleResponse\"8\x92A\x1a\n" +
	"\bArticles\x12\x0eCreate Article\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/articles\x12\x91\x01\n" +
	"\aGetByID\x12\".userservice.GetArticleByIDRequest\x1a#.userservice.GetArticleByIDResponse\"=\x92A\x1d\n" +
	"\bArticles\x12\x11Get Article By ID\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/articles/{id}\x12\x81\x01\n" +
	"\x04List\x12 .userservice.ListArticlesRequest\x1a!.userservice.ListArticlesResponse\"4\x92A\x19\n" +
	"\bArticles\x12\rList Articles\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/articles\x12\x8e\x01\n" +
	"\x06Update\x12!.userservice.UpdateArticleRequest\x1a\".userservice.UpdateArticleResponse\"=\x92A\x1a\n" +
	"\bArticles\x12\x0eUpdate Article\x82\xd3\xe4\x93\x02\x1a:\x01*2\x15/api/v1/articles/{id}\x12\x7f\n" +
	"\x06Delete\x12!.userservice.DeleteArticleRequest\x1a\x16.google.protobuf.Empty\":\x92A\x1a\n" +
	"\bArticles\x12\x0eDelete Article\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/articles/{id}\x1a#\x92A \x12\x1eOperations related to articlesB\xf9\x01\x92A\xc0\x01\x126\n" +
	"\x13Article Service API\x12\x1aAPI for managing articles.2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZL\n" +
	"J\n" +
	"\n" +
	"BearerAuth\x12<\b\x02\x12'JWT Bearer token (e.g., 'Bearer ey...')\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00Z3golang-microservices-boilerplate/proto/user-serviceb\x06proto3"

var (
	file_proto_user_service_article_proto_rawDescOnce sync.Once
	file_proto_user_service_article_proto_rawDescData []byte
)

func file_proto_user_service_article_proto_rawDescGZIP() []byte {
	file_proto_user_service_article_proto_rawDescOnce.Do(func() {
		file_proto_user_service_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_service_article_proto_rawDesc), len(file_proto_user_service_article_proto_rawDesc)))
	})
	return file_proto_user_service_article_proto_rawDescData
}

var file_proto_user_service_article_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_user_service_article_proto_goTypes = []any{
	(*Article)(nil),                // 0: userservice.Article
	(*CreateArticleRequest)(nil),   // 1: userservice.CreateArticleRequest
	(*CreateArticleResponse)(nil),  // 2: userservice.CreateArticleResponse
	(*GetArticleByIDRequest)(nil),  // 3: userservice.GetArticleByIDRequest
	(*GetArticleByIDResponse)(nil), // 4: userservice.GetArticleByIDResponse
	(*ListArticlesRequest)(nil),    // 5: userservice.ListArticlesRequest
	(*ListArticlesResponse)(nil),   // 6: userservice.ListArticlesResponse
	(*UpdateArticleRequest)(nil),   // 7: userservice.UpdateArticleRequest
	(*FileIDsUpdate)(nil),          // 8: userservice.FileIDsUpdate
	(*UpdateArticleResponse)(nil),  // 9: userservice.UpdateArticleResponse
	(*DeleteArticleRequest)(nil),   // 10: userservice.DeleteArticleRequest
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
	(*core.FilterOptions)(nil),     // 12: core.FilterOptions
	(*core.PaginationInfo)(nil),    // 13: core.PaginationInfo
	(*wrapperspb.StringValue)(nil), // 14: google.protobuf.StringValue
	(*emptypb.Empty)(nil),          // 15: google.protobuf.Empty
}
var file_proto_user_service_article_proto_depIdxs = []int32{
	11, // 0: userservice.Article.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: userservice.Article.updated_at:type_name -> google.protobuf.Timestamp
	11, // 2: userservice.Article.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: userservice.CreateArticleResponse.article:type_name -> userservice.Article
	0,  // 4: userservice.GetArticleByIDResponse.article:type_name -> userservice.Article
	12, // 5: userservice.ListArticlesRequest.options:type_name -> core.FilterOptions
	0,  // 6: userservice.ListArticlesResponse.articles:type_name -> userservice.Article
	13, // 7: userservice.ListArticlesResponse.pagination_info:type_name -> core.PaginationInfo
	14, // 8: userservice.UpdateArticleRequest.title:type_name -> google.protobuf.StringValue
	14, // 9: userservice.UpdateArticleRequest.content:type_name -> google.protobuf.StringValue
	14, // 10: userservice.UpdateArticleRequest.picture_url:type_name -> google.protobuf.StringValue
	14, // 11: userservice.UpdateArticleRequest.badge:type_name -> google.protobuf.StringValue
	8,  // 12: userservice.UpdateArticleRequest.file_ids:type_name -> userservice.FileIDsUpdate
	0,  // 13: userservice.UpdateArticleResponse.article:type_name -> userservice.Article
	1,  // 14: userservice.ArticleService.Create:input_type -> userservice.CreateArticleRequest
	3,  // 15: userservice.ArticleService.GetByID:input_type -> userservice.GetArticleByIDRequest
	5,  // 16: userservice.ArticleService.List:input_type -> userservice.ListArticlesRequest
	7,  // 17: userservice.ArticleService.Update:input_type -> userservice.UpdateArticleRequest
	10, // 18: userservice.ArticleService.Delete:input_type -> userservice.DeleteArticleRequest
	2,  // 19: userservice.ArticleService.Create:output_type -> userservice.CreateArticleResponse
	4,  // 20: userservice.ArticleService.GetByID:output_type -> userservice.GetArticleByIDResponse
	6,  // 21: userservice.ArticleService.List:output_type -> userservice.ListArticlesResponse
	9,  // 22: userservice.ArticleService.Update:output_type -> userservice.UpdateArticleResponse
	15, // 23: userservice.ArticleService.Delete:output_type -> google.protobuf.Empty
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_user_service_article_proto_init() }
func file_proto_user_service_article_proto_init() {
	if File_proto_user_service_article_proto != nil {
		return
	}
	file_proto_user_service_article_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_user_service_article_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_user_service_article_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_service_article_proto_rawDesc), len(file_proto_user_service_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_service_article_proto_goTypes,
		DependencyIndexes: file_proto_user_service_article_proto_depIdxs,
		MessageInfos:      file_proto_user_service_article_proto_msgTypes,
	}.Build()
	File_proto_user_service_article_proto = out.File
	file_proto_user_service_article_proto_goTypes = nil
	file_proto_user_service_article_proto_depIdxs = nil
}
