// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/user-service/notification.proto

package user_service

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	core "golang-microservices-boilerplate/proto/core"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Notification Message ---
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Read          bool                   `protobuf:"varint,7,opt,name=read,proto3" json:"read,omitempty"` // Corrected boolean example
	UserId        string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_user_service_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Notification) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Notification) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Create
type CreateNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 'read' defaults to false server-side
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationRequest) Reset() {
	*x = CreateNotificationRequest{}
	mi := &file_proto_user_service_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRequest) ProtoMessage() {}

func (x *CreateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNotificationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationResponse) Reset() {
	*x = CreateNotificationResponse{}
	mi := &file_proto_user_service_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationResponse) ProtoMessage() {}

func (x *CreateNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationResponse.ProtoReflect.Descriptor instead.
func (*CreateNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

// Get By ID
type GetNotificationByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationByIDRequest) Reset() {
	*x = GetNotificationByIDRequest{}
	mi := &file_proto_user_service_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationByIDRequest) ProtoMessage() {}

func (x *GetNotificationByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationByIDRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotificationByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNotificationByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationByIDResponse) Reset() {
	*x = GetNotificationByIDResponse{}
	mi := &file_proto_user_service_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationByIDResponse) ProtoMessage() {}

func (x *GetNotificationByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationByIDResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetNotificationByIDResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

// List (Standard)
type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *core.FilterOptions    `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_proto_user_service_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ListNotificationsRequest) GetOptions() *core.FilterOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListNotificationsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Notifications  []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	PaginationInfo *core.PaginationInfo   `protobuf:"bytes,2,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_proto_user_service_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetPaginationInfo() *core.PaginationInfo {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

// Update
type UpdateNotificationRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Read          *wrapperspb.BoolValue   `protobuf:"bytes,4,opt,name=read,proto3,oneof" json:"read,omitempty"` // Corrected boolean example
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationRequest) Reset() {
	*x = UpdateNotificationRequest{}
	mi := &file_proto_user_service_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationRequest) ProtoMessage() {}

func (x *UpdateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateNotificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNotificationRequest) GetTitle() *wrapperspb.StringValue {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *UpdateNotificationRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdateNotificationRequest) GetRead() *wrapperspb.BoolValue {
	if x != nil {
		return x.Read
	}
	return nil
}

type UpdateNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationResponse) Reset() {
	*x = UpdateNotificationResponse{}
	mi := &file_proto_user_service_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationResponse) ProtoMessage() {}

func (x *UpdateNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

// Delete
type DeleteNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HardDelete    bool                   `protobuf:"varint,2,opt,name=hard_delete,json=hardDelete,proto3" json:"hard_delete,omitempty"` // Corrected boolean example
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationRequest) Reset() {
	*x = DeleteNotificationRequest{}
	mi := &file_proto_user_service_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRequest) ProtoMessage() {}

func (x *DeleteNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteNotificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteNotificationRequest) GetHardDelete() bool {
	if x != nil {
		return x.HardDelete
	}
	return false
}

// Find By User
type FindByUserRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Optional filter for read status (maps to query parameter ?read=true or ?read=false)
	Read          *bool               `protobuf:"varint,2,opt,name=read,proto3,oneof" json:"read,omitempty"` // Corrected boolean example
	Options       *core.FilterOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`  // For pagination/sorting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByUserRequest) Reset() {
	*x = FindByUserRequest{}
	mi := &file_proto_user_service_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByUserRequest) ProtoMessage() {}

func (x *FindByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByUserRequest.ProtoReflect.Descriptor instead.
func (*FindByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{10}
}

func (x *FindByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindByUserRequest) GetRead() bool {
	if x != nil && x.Read != nil {
		return *x.Read
	}
	return false
}

func (x *FindByUserRequest) GetOptions() *core.FilterOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type FindByUserResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Notifications  []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	PaginationInfo *core.PaginationInfo   `protobuf:"bytes,2,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindByUserResponse) Reset() {
	*x = FindByUserResponse{}
	mi := &file_proto_user_service_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByUserResponse) ProtoMessage() {}

func (x *FindByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByUserResponse.ProtoReflect.Descriptor instead.
func (*FindByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{11}
}

func (x *FindByUserResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *FindByUserResponse) GetPaginationInfo() *core.PaginationInfo {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

// Mark As Read
type MarkNotificationsAsReadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NotificationIds []string               `protobuf:"bytes,1,rep,name=notification_ids,json=notificationIds,proto3" json:"notification_ids,omitempty"` // Corrected repeated string example
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkNotificationsAsReadRequest) Reset() {
	*x = MarkNotificationsAsReadRequest{}
	mi := &file_proto_user_service_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationsAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationsAsReadRequest) ProtoMessage() {}

func (x *MarkNotificationsAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationsAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkNotificationsAsReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{12}
}

func (x *MarkNotificationsAsReadRequest) GetNotificationIds() []string {
	if x != nil {
		return x.NotificationIds
	}
	return nil
}

// --- Bulk Create --- (New Messages)
type CreateNotificationsRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Notifications []*CreateNotificationRequest `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationsRequest) Reset() {
	*x = CreateNotificationsRequest{}
	mi := &file_proto_user_service_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationsRequest) ProtoMessage() {}

func (x *CreateNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationsRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{13}
}

func (x *CreateNotificationsRequest) GetNotifications() []*CreateNotificationRequest {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type CreateNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationsResponse) Reset() {
	*x = CreateNotificationsResponse{}
	mi := &file_proto_user_service_notification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationsResponse) ProtoMessage() {}

func (x *CreateNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_notification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationsResponse.ProtoReflect.Descriptor instead.
func (*CreateNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_notification_proto_rawDescGZIP(), []int{14}
}

func (x *CreateNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

var File_proto_user_service_notification_proto protoreflect.FileDescriptor

const file_proto_user_service_notification_proto_rawDesc = "" +
	"\n" +
	"%proto/user-service/notification.proto\x12\vuserservice\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17proto/core/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xaa\a\n" +
	"\fNotification\x12J\n" +
	"\x02id\x18\x01 \x01(\tB:\x92A72\x19Unique identifier (UUID).J\x1a\"notification-uuid-string\"R\x02id\x12k\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB0\x92A-2\x13Creation timestamp.J\x16\"2023-10-27T10:00:00Z\"R\tcreatedAt\x12n\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB3\x92A02\x16Last update timestamp.J\x16\"2023-10-27T11:30:00Z\"R\tupdatedAt\x12\x82\x01\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampBB\x92A?2%Deletion timestamp (if soft-deleted).J\x16\"2023-10-28T09:15:00Z\"H\x00R\tdeletedAt\x88\x01\x01\x12F\n" +
	"\x05title\x18\x05 \x01(\tB0\x92A-2\x13Notification title.J\x16\"New Message Received\"R\x05title\x12e\n" +
	"\vdescription\x18\x06 \x01(\tBC\x92A@2\x15Notification details.J'\"You have a new message from John Doe.\"R\vdescription\x12G\n" +
	"\x04read\x18\a \x01(\bB3\x92A02'Whether the notification has been read.J\x05falseR\x04read\x12a\n" +
	"\auser_id\x18\b \x01(\tBH\x92AE2/ID (UUID) of the user this notification is for.J\x12\"user-uuid-string\"R\x06userId:\x81\x01\x92A~\n" +
	"|*\fNotification2&Represents a user notification entity.\xd2\x01\x02id\xd2\x01\n" +
	"created_at\xd2\x01\n" +
	"updated_at\xd2\x01\x05title\xd2\x01\vdescription\xd2\x01\x04read\xd2\x01\auser_idB\r\n" +
	"\v_deleted_at\"\xcb\x02\n" +
	"\x19CreateNotificationRequest\x12?\n" +
	"\x05title\x18\x01 \x01(\tB)\x92A&2\x13Notification title.J\x0f\"Task Reminder\"R\x05title\x12_\n" +
	"\vdescription\x18\x02 \x01(\tB=\x92A:2\x15Notification details.J!\"Remember to submit your report.\"R\vdescription\x12H\n" +
	"\auser_id\x18\x03 \x01(\tB/\x92A,2\x16Target user ID (UUID).J\x12\"user-uuid-string\"R\x06userId:B\x92A?\n" +
	"=*\x1bCreate Notification Request\xd2\x01\x05title\xd2\x01\vdescription\xd2\x01\auser_id\"\x80\x01\n" +
	"\x1aCreateNotificationResponse\x12=\n" +
	"\fnotification\x18\x01 \x01(\v2\x19.userservice.NotificationR\fnotification:#\x92A \n" +
	"\x1e*\x1cCreate Notification Response\"\xa0\x01\n" +
	"\x1aGetNotificationByIDRequest\x12V\n" +
	"\x02id\x18\x01 \x01(\tBF\x92AC2%UUID of the notification to retrieve.J\x1a\"notification-uuid-string\"R\x02id:*\x92A'\n" +
	"%*\x1eGet Notification By ID Request\xd2\x01\x02id\"\x84\x01\n" +
	"\x1bGetNotificationByIDResponse\x12=\n" +
	"\fnotification\x18\x01 \x01(\v2\x19.userservice.NotificationR\fnotification:&\x92A#\n" +
	"!*\x1fGet Notification By ID Response\"l\n" +
	"\x18ListNotificationsRequest\x12-\n" +
	"\aoptions\x18\x01 \x01(\v2\x13.core.FilterOptionsR\aoptions:!\x92A\x1e\n" +
	"\x1c*\x1aList Notifications Request\"\xbf\x01\n" +
	"\x19ListNotificationsResponse\x12?\n" +
	"\rnotifications\x18\x01 \x03(\v2\x19.userservice.NotificationR\rnotifications\x12=\n" +
	"\x0fpagination_info\x18\x02 \x01(\v2\x14.core.PaginationInfoR\x0epaginationInfo:\"\x92A\x1f\n" +
	"\x1d*\x1bList Notifications Response\"\xe0\x03\n" +
	"\x19UpdateNotificationRequest\x12T\n" +
	"\x02id\x18\x01 \x01(\tBD\x92AA2#UUID of the notification to update.J\x1a\"notification-uuid-string\"R\x02id\x12Y\n" +
	"\x05title\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueB \x92A\x1d2\n" +
	"New title.J\x0f\"Updated Title\"H\x00R\x05title\x88\x01\x01\x12t\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueB/\x92A,2\x10New description.J\x18\"Updated description...\"H\x01R\vdescription\x88\x01\x01\x12P\n" +
	"\x04read\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueB\x1b\x92A\x182\x10New read status.J\x04trueH\x02R\x04read\x88\x01\x01:'\x92A$\n" +
	"\"*\x1bUpdate Notification Request\xd2\x01\x02idB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_read\"\x80\x01\n" +
	"\x1aUpdateNotificationResponse\x12=\n" +
	"\fnotification\x18\x01 \x01(\v2\x19.userservice.NotificationR\fnotification:#\x92A \n" +
	"\x1e*\x1cUpdate Notification Response\"\xec\x01\n" +
	"\x19DeleteNotificationRequest\x12T\n" +
	"\x02id\x18\x01 \x01(\tBD\x92AA2#UUID of the notification to delete.J\x1a\"notification-uuid-string\"R\x02id\x12P\n" +
	"\vhard_delete\x18\x02 \x01(\bB/\x92A,2\x1cPerform hard delete if true.:\x05falseJ\x05falseR\n" +
	"hardDelete:'\x92A$\n" +
	"\"*\x1bDelete Notification Request\xd2\x01\x02id\"\x84\x02\n" +
	"\x11FindByUserRequest\x12H\n" +
	"\auser_id\x18\x01 \x01(\tB/\x92A,2\x16Target user ID (UUID).J\x12\"user-uuid-string\"R\x06userId\x12F\n" +
	"\x04read\x18\x02 \x01(\bB-\x92A*2!Filter by read status (optional).J\x05falseH\x00R\x04read\x88\x01\x01\x12-\n" +
	"\aoptions\x18\x03 \x01(\v2\x13.core.FilterOptionsR\aoptions:%\x92A\"\n" +
	" *\x14Find By User Request\xd2\x01\auser_idB\a\n" +
	"\x05_read\"\xb2\x01\n" +
	"\x12FindByUserResponse\x12?\n" +
	"\rnotifications\x18\x01 \x03(\v2\x19.userservice.NotificationR\rnotifications\x12=\n" +
	"\x0fpagination_info\x18\x02 \x01(\v2\x14.core.PaginationInfoR\x0epaginationInfo:\x1c\x92A\x19\n" +
	"\x17*\x15Find By User Response\"\xdb\x01\n" +
	"\x1eMarkNotificationsAsReadRequest\x12{\n" +
	"\x10notification_ids\x18\x01 \x03(\tBP\x92AM2+List of notification UUIDs to mark as read.J\x1e[\"noti-uuid-1\", \"noti-uuid-2\"]R\x0fnotificationIds:<\x92A9\n" +
	"7*\"Mark Notifications As Read Request\xd2\x01\x10notification_ids\"\xd1\x01\n" +
	"\x1aCreateNotificationsRequest\x12u\n" +
	"\rnotifications\x18\x01 \x03(\v2&.userservice.CreateNotificationRequestB'\x92A$2\"A list of notifications to create.R\rnotifications:<\x92A9\n" +
	"7*%Create Multiple Notifications Request\xd2\x01\rnotifications\"\xbc\x01\n" +
	"\x1bCreateNotificationsResponse\x12n\n" +
	"\rnotifications\x18\x01 \x03(\v2\x19.userservice.NotificationB-\x92A*2(The list of newly created notifications.R\rnotifications:-\x92A*\n" +
	"(*&Create Multiple Notifications Response2\x88\v\n" +
	"\x13NotificationService\x12\xa2\x01\n" +
	"\x06Create\x12&.userservice.CreateNotificationRequest\x1a'.userservice.CreateNotificationResponse\"G\x92A$\n" +
	"\rNotifications\x12\x13Create Notification\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/notifications\x12\xb7\x01\n" +
	"\n" +
	"CreateMany\x12'.userservice.CreateNotificationsRequest\x1a(.userservice.CreateNotificationsResponse\"V\x92A.\n" +
	"\rNotifications\x12\x1dCreate Multiple Notifications\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/notifications/bulk\x12\xaa\x01\n" +
	"\aGetByID\x12'.userservice.GetNotificationByIDRequest\x1a(.userservice.GetNotificationByIDResponse\"L\x92A'\n" +
	"\rNotifications\x12\x16Get Notification By ID\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/notifications/{id}\x12\x9a\x01\n" +
	"\x04List\x12%.userservice.ListNotificationsRequest\x1a&.userservice.ListNotificationsResponse\"C\x92A#\n" +
	"\rNotifications\x12\x12List Notifications\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/notifications\x12\xa7\x01\n" +
	"\x06Update\x12&.userservice.UpdateNotificationRequest\x1a'.userservice.UpdateNotificationResponse\"L\x92A$\n" +
	"\rNotifications\x12\x13Update Notification\x82\xd3\xe4\x93\x02\x1f:\x01*2\x1a/api/v1/notifications/{id}\x12\x93\x01\n" +
	"\x06Delete\x12&.userservice.DeleteNotificationRequest\x1a\x16.google.protobuf.Empty\"I\x92A$\n" +
	"\rNotifications\x12\x13Delete Notification\x82\xd3\xe4\x93\x02\x1c*\x1a/api/v1/notifications/{id}\x12\xaa\x01\n" +
	"\n" +
	"FindByUser\x12\x1e.userservice.FindByUserRequest\x1a\x1f.userservice.FindByUserResponse\"[\x92A+\n" +
	"\rNotifications\x12\x1aFind Notifications By User\x82\xd3\xe4\x93\x02'\x12%/api/v1/users/{user_id}/notifications\x12\xab\x01\n" +
	"\n" +
	"MarkAsRead\x12+.userservice.MarkNotificationsAsReadRequest\x1a\x16.google.protobuf.Empty\"X\x92A+\n" +
	"\rNotifications\x12\x1aMark Notifications As Read\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/notifications/mark-read\x1a-\x92A*\x12(Operations related to user notificationsB\x88\x02\x92A\xcf\x01\x12E\n" +
	"\x18Notification Service API\x12$API for managing user notifications.2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZL\n" +
	"J\n" +
	"\n" +
	"BearerAuth\x12<\b\x02\x12'JWT Bearer token (e.g., 'Bearer ey...')\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00Z3golang-microservices-boilerplate/proto/user-serviceb\x06proto3"

var (
	file_proto_user_service_notification_proto_rawDescOnce sync.Once
	file_proto_user_service_notification_proto_rawDescData []byte
)

func file_proto_user_service_notification_proto_rawDescGZIP() []byte {
	file_proto_user_service_notification_proto_rawDescOnce.Do(func() {
		file_proto_user_service_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_service_notification_proto_rawDesc), len(file_proto_user_service_notification_proto_rawDesc)))
	})
	return file_proto_user_service_notification_proto_rawDescData
}

var file_proto_user_service_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_user_service_notification_proto_goTypes = []any{
	(*Notification)(nil),                   // 0: userservice.Notification
	(*CreateNotificationRequest)(nil),      // 1: userservice.CreateNotificationRequest
	(*CreateNotificationResponse)(nil),     // 2: userservice.CreateNotificationResponse
	(*GetNotificationByIDRequest)(nil),     // 3: userservice.GetNotificationByIDRequest
	(*GetNotificationByIDResponse)(nil),    // 4: userservice.GetNotificationByIDResponse
	(*ListNotificationsRequest)(nil),       // 5: userservice.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),      // 6: userservice.ListNotificationsResponse
	(*UpdateNotificationRequest)(nil),      // 7: userservice.UpdateNotificationRequest
	(*UpdateNotificationResponse)(nil),     // 8: userservice.UpdateNotificationResponse
	(*DeleteNotificationRequest)(nil),      // 9: userservice.DeleteNotificationRequest
	(*FindByUserRequest)(nil),              // 10: userservice.FindByUserRequest
	(*FindByUserResponse)(nil),             // 11: userservice.FindByUserResponse
	(*MarkNotificationsAsReadRequest)(nil), // 12: userservice.MarkNotificationsAsReadRequest
	(*CreateNotificationsRequest)(nil),     // 13: userservice.CreateNotificationsRequest
	(*CreateNotificationsResponse)(nil),    // 14: userservice.CreateNotificationsResponse
	(*timestamppb.Timestamp)(nil),          // 15: google.protobuf.Timestamp
	(*core.FilterOptions)(nil),             // 16: core.FilterOptions
	(*core.PaginationInfo)(nil),            // 17: core.PaginationInfo
	(*wrapperspb.StringValue)(nil),         // 18: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),           // 19: google.protobuf.BoolValue
	(*emptypb.Empty)(nil),                  // 20: google.protobuf.Empty
}
var file_proto_user_service_notification_proto_depIdxs = []int32{
	15, // 0: userservice.Notification.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: userservice.Notification.updated_at:type_name -> google.protobuf.Timestamp
	15, // 2: userservice.Notification.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: userservice.CreateNotificationResponse.notification:type_name -> userservice.Notification
	0,  // 4: userservice.GetNotificationByIDResponse.notification:type_name -> userservice.Notification
	16, // 5: userservice.ListNotificationsRequest.options:type_name -> core.FilterOptions
	0,  // 6: userservice.ListNotificationsResponse.notifications:type_name -> userservice.Notification
	17, // 7: userservice.ListNotificationsResponse.pagination_info:type_name -> core.PaginationInfo
	18, // 8: userservice.UpdateNotificationRequest.title:type_name -> google.protobuf.StringValue
	18, // 9: userservice.UpdateNotificationRequest.description:type_name -> google.protobuf.StringValue
	19, // 10: userservice.UpdateNotificationRequest.read:type_name -> google.protobuf.BoolValue
	0,  // 11: userservice.UpdateNotificationResponse.notification:type_name -> userservice.Notification
	16, // 12: userservice.FindByUserRequest.options:type_name -> core.FilterOptions
	0,  // 13: userservice.FindByUserResponse.notifications:type_name -> userservice.Notification
	17, // 14: userservice.FindByUserResponse.pagination_info:type_name -> core.PaginationInfo
	1,  // 15: userservice.CreateNotificationsRequest.notifications:type_name -> userservice.CreateNotificationRequest
	0,  // 16: userservice.CreateNotificationsResponse.notifications:type_name -> userservice.Notification
	1,  // 17: userservice.NotificationService.Create:input_type -> userservice.CreateNotificationRequest
	13, // 18: userservice.NotificationService.CreateMany:input_type -> userservice.CreateNotificationsRequest
	3,  // 19: userservice.NotificationService.GetByID:input_type -> userservice.GetNotificationByIDRequest
	5,  // 20: userservice.NotificationService.List:input_type -> userservice.ListNotificationsRequest
	7,  // 21: userservice.NotificationService.Update:input_type -> userservice.UpdateNotificationRequest
	9,  // 22: userservice.NotificationService.Delete:input_type -> userservice.DeleteNotificationRequest
	10, // 23: userservice.NotificationService.FindByUser:input_type -> userservice.FindByUserRequest
	12, // 24: userservice.NotificationService.MarkAsRead:input_type -> userservice.MarkNotificationsAsReadRequest
	2,  // 25: userservice.NotificationService.Create:output_type -> userservice.CreateNotificationResponse
	14, // 26: userservice.NotificationService.CreateMany:output_type -> userservice.CreateNotificationsResponse
	4,  // 27: userservice.NotificationService.GetByID:output_type -> userservice.GetNotificationByIDResponse
	6,  // 28: userservice.NotificationService.List:output_type -> userservice.ListNotificationsResponse
	8,  // 29: userservice.NotificationService.Update:output_type -> userservice.UpdateNotificationResponse
	20, // 30: userservice.NotificationService.Delete:output_type -> google.protobuf.Empty
	11, // 31: userservice.NotificationService.FindByUser:output_type -> userservice.FindByUserResponse
	20, // 32: userservice.NotificationService.MarkAsRead:output_type -> google.protobuf.Empty
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_user_service_notification_proto_init() }
func file_proto_user_service_notification_proto_init() {
	if File_proto_user_service_notification_proto != nil {
		return
	}
	file_proto_user_service_notification_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_user_service_notification_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_user_service_notification_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_service_notification_proto_rawDesc), len(file_proto_user_service_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_service_notification_proto_goTypes,
		DependencyIndexes: file_proto_user_service_notification_proto_depIdxs,
		MessageInfos:      file_proto_user_service_notification_proto_msgTypes,
	}.Build()
	File_proto_user_service_notification_proto = out.File
	file_proto_user_service_notification_proto_goTypes = nil
	file_proto_user_service_notification_proto_depIdxs = nil
}
