// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/user-service/request.proto

package user_service

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	core "golang-microservices-boilerplate/proto/core"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Request Message ---
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	SenderId      string                 `protobuf:"bytes,6,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,7,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	FileIds       []string               `protobuf:"bytes,9,rep,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"` // Corrected repeated string example
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`       // Added description field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_user_service_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Request) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Request) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Request) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Request) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Request) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Request) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Request) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

func (x *Request) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Create
type CreateRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	FileIds       []string               `protobuf:"bytes,5,rep,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"` // Corrected repeated string example
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`        // Added optional description field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequestRequest) Reset() {
	*x = CreateRequestRequest{}
	mi := &file_proto_user_service_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestRequest) ProtoMessage() {}

func (x *CreateRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequestRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRequestRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *CreateRequestRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *CreateRequestRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateRequestRequest) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

func (x *CreateRequestRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *Request               `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequestResponse) Reset() {
	*x = CreateRequestResponse{}
	mi := &file_proto_user_service_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestResponse) ProtoMessage() {}

func (x *CreateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequestResponse) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

// Get By ID
type GetRequestByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestByIDRequest) Reset() {
	*x = GetRequestByIDRequest{}
	mi := &file_proto_user_service_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestByIDRequest) ProtoMessage() {}

func (x *GetRequestByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestByIDRequest.ProtoReflect.Descriptor instead.
func (*GetRequestByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequestByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRequestByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *Request               `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestByIDResponse) Reset() {
	*x = GetRequestByIDResponse{}
	mi := &file_proto_user_service_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestByIDResponse) ProtoMessage() {}

func (x *GetRequestByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestByIDResponse.ProtoReflect.Descriptor instead.
func (*GetRequestByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequestByIDResponse) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

// List (Standard)
type ListRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *core.FilterOptions    `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsRequest) Reset() {
	*x = ListRequestsRequest{}
	mi := &file_proto_user_service_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsRequest) ProtoMessage() {}

func (x *ListRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListRequestsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequestsRequest) GetOptions() *core.FilterOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListRequestsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Requests       []*Request             `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	PaginationInfo *core.PaginationInfo   `protobuf:"bytes,2,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListRequestsResponse) Reset() {
	*x = ListRequestsResponse{}
	mi := &file_proto_user_service_request_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsResponse) ProtoMessage() {}

func (x *ListRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListRequestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequestsResponse) GetRequests() []*Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ListRequestsResponse) GetPaginationInfo() *core.PaginationInfo {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

// Update
type UpdateRequestRequest struct {
	state protoimpl.MessageState  `protogen:"open.v1"`
	Id    string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// sender_id and receiver_id typically shouldn't be updated
	Status *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	// Use the FileIDsUpdate message (defined above or imported)
	FileIds       *FileIDsUpdate          `protobuf:"bytes,4,opt,name=file_ids,json=fileIds,proto3,oneof" json:"file_ids,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"` // Added optional description field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequestRequest) Reset() {
	*x = UpdateRequestRequest{}
	mi := &file_proto_user_service_request_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequestRequest) ProtoMessage() {}

func (x *UpdateRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequestRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRequestRequest) GetTitle() *wrapperspb.StringValue {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *UpdateRequestRequest) GetStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UpdateRequestRequest) GetFileIds() *FileIDsUpdate {
	if x != nil {
		return x.FileIds
	}
	return nil
}

func (x *UpdateRequestRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

type UpdateRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *Request               `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequestResponse) Reset() {
	*x = UpdateRequestResponse{}
	mi := &file_proto_user_service_request_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequestResponse) ProtoMessage() {}

func (x *UpdateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequestResponse.ProtoReflect.Descriptor instead.
func (*UpdateRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRequestResponse) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

// Delete
type DeleteRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HardDelete    bool                   `protobuf:"varint,2,opt,name=hard_delete,json=hardDelete,proto3" json:"hard_delete,omitempty"` // Corrected boolean example
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequestRequest) Reset() {
	*x = DeleteRequestRequest{}
	mi := &file_proto_user_service_request_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequestRequest) ProtoMessage() {}

func (x *DeleteRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequestRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequestRequest) GetHardDelete() bool {
	if x != nil {
		return x.HardDelete
	}
	return false
}

// Find By User Participant
type FindByUserParticipantRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Optional filter for status (maps to query parameter ?status=pending etc.)
	Status        *string             `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Options       *core.FilterOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"` // For pagination/sorting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByUserParticipantRequest) Reset() {
	*x = FindByUserParticipantRequest{}
	mi := &file_proto_user_service_request_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByUserParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByUserParticipantRequest) ProtoMessage() {}

func (x *FindByUserParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByUserParticipantRequest.ProtoReflect.Descriptor instead.
func (*FindByUserParticipantRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{10}
}

func (x *FindByUserParticipantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindByUserParticipantRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *FindByUserParticipantRequest) GetOptions() *core.FilterOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type FindByUserParticipantResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Requests       []*Request             `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	PaginationInfo *core.PaginationInfo   `protobuf:"bytes,2,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindByUserParticipantResponse) Reset() {
	*x = FindByUserParticipantResponse{}
	mi := &file_proto_user_service_request_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByUserParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByUserParticipantResponse) ProtoMessage() {}

func (x *FindByUserParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_service_request_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByUserParticipantResponse.ProtoReflect.Descriptor instead.
func (*FindByUserParticipantResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_service_request_proto_rawDescGZIP(), []int{11}
}

func (x *FindByUserParticipantResponse) GetRequests() []*Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *FindByUserParticipantResponse) GetPaginationInfo() *core.PaginationInfo {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

var File_proto_user_service_request_proto protoreflect.FileDescriptor

const file_proto_user_service_request_proto_rawDesc = "" +
	"\n" +
	" proto/user-service/request.proto\x12\vuserservice\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17proto/core/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a proto/user-service/article.proto\"\x88\t\n" +
	"\aRequest\x12E\n" +
	"\x02id\x18\x01 \x01(\tB5\x92A22\x19Unique identifier (UUID).J\x15\"request-uuid-string\"R\x02id\x12k\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB0\x92A-2\x13Creation timestamp.J\x16\"2023-10-27T10:00:00Z\"R\tcreatedAt\x12n\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB3\x92A02\x16Last update timestamp.J\x16\"2023-10-27T11:30:00Z\"R\tupdatedAt\x12\x82\x01\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampBB\x92A?2%Deletion timestamp (if soft-deleted).J\x16\"2023-10-28T09:15:00Z\"H\x00R\tdeletedAt\x88\x01\x01\x12E\n" +
	"\x05title\x18\x05 \x01(\tB/\x92A,2\x0eRequest title.J\x1a\"Leave Request - Dec 2023\"R\x05title\x12P\n" +
	"\tsender_id\x18\x06 \x01(\tB3\x92A02\x18Sender's user ID (UUID).J\x14\"sender-uuid-string\"R\bsenderId\x12X\n" +
	"\vreceiver_id\x18\a \x01(\tB7\x92A42\x1aReceiver's user ID (UUID).J\x16\"receiver-uuid-string\"R\n" +
	"receiverId\x12p\n" +
	"\x06status\x18\b \x01(\tBX\x92AU2HCurrent status of the request (e.g., 'pending', 'approved', 'rejected').J\t\"pending\"R\x06status\x12d\n" +
	"\bfile_ids\x18\t \x03(\tBI\x92AF2$List of associated file IDs (UUIDs).J\x1e[\"file-uuid-1\", \"file-uuid-2\"]R\afileIds\x12r\n" +
	"\vdescription\x18\n" +
	" \x01(\tBP\x92AM2%Optional description for the request.J$\"Requesting leave for family event.\"R\vdescription:\x85\x01\x92A\x81\x01\n" +
	"\x7f*\aRequest2*Represents a request entity between users.\xd2\x01\x02id\xd2\x01\n" +
	"created_at\xd2\x01\n" +
	"updated_at\xd2\x01\x05title\xd2\x01\tsender_id\xd2\x01\vreceiver_id\xd2\x01\x06statusB\r\n" +
	"\v_deleted_at\"\xf6\x04\n" +
	"\x14CreateRequestRequest\x12F\n" +
	"\x05title\x18\x01 \x01(\tB0\x92A-2\x0eRequest title.J\x1b\"Document Approval Request\"R\x05title\x12P\n" +
	"\tsender_id\x18\x02 \x01(\tB3\x92A02\x18Sender's user ID (UUID).J\x14\"sender-uuid-string\"R\bsenderId\x12X\n" +
	"\vreceiver_id\x18\x03 \x01(\tB7\x92A42\x1aReceiver's user ID (UUID).J\x16\"receiver-uuid-string\"R\n" +
	"receiverId\x12I\n" +
	"\x06status\x18\x04 \x01(\tB1\x92A.2!Initial status (e.g., 'pending').J\t\"pending\"R\x06status\x12_\n" +
	"\bfile_ids\x18\x05 \x03(\tBD\x92AA2.List of associated file IDs (UUIDs, optional).J\x0f[\"file-uuid-1\"]R\afileIds\x12t\n" +
	"\vdescription\x18\x06 \x01(\tBR\x92AO2%Optional description for the request.J&\"Please review the attached proposal.\"R\vdescription:H\x92AE\n" +
	"C*\x16Create Request Request\xd2\x01\x05title\xd2\x01\tsender_id\xd2\x01\vreceiver_id\xd2\x01\x06status\"g\n" +
	"\x15CreateRequestResponse\x12.\n" +
	"\arequest\x18\x01 \x01(\v2\x14.userservice.RequestR\arequest:\x1e\x92A\x1b\n" +
	"\x19*\x17Create Request Response\"\x8c\x01\n" +
	"\x15GetRequestByIDRequest\x12L\n" +
	"\x02id\x18\x01 \x01(\tB<\x92A92 UUID of the request to retrieve.J\x15\"request-uuid-string\"R\x02id:%\x92A\"\n" +
	" *\x19Get Request By ID Request\xd2\x01\x02id\"k\n" +
	"\x16GetRequestByIDResponse\x12.\n" +
	"\arequest\x18\x01 \x01(\v2\x14.userservice.RequestR\arequest:!\x92A\x1e\n" +
	"\x1c*\x1aGet Request By ID Response\"b\n" +
	"\x13ListRequestsRequest\x12-\n" +
	"\aoptions\x18\x01 \x01(\v2\x13.core.FilterOptionsR\aoptions:\x1c\x92A\x19\n" +
	"\x17*\x15List Requests Request\"\xa6\x01\n" +
	"\x14ListRequestsResponse\x120\n" +
	"\brequests\x18\x01 \x03(\v2\x14.userservice.RequestR\brequests\x12=\n" +
	"\x0fpagination_info\x18\x02 \x01(\v2\x14.core.PaginationInfoR\x0epaginationInfo:\x1d\x92A\x1a\n" +
	"\x18*\x16List Requests Response\"\xf2\x04\n" +
	"\x14UpdateRequestRequest\x12J\n" +
	"\x02id\x18\x01 \x01(\tB:\x92A72\x1eUUID of the request to update.J\x15\"request-uuid-string\"R\x02id\x12a\n" +
	"\x05title\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueB(\x92A%2\n" +
	"New title.J\x17\"Updated Request Title\"H\x00R\x05title\x88\x01\x01\x12v\n" +
	"\x06status\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueB;\x92A82*New status (e.g., 'approved', 'rejected').J\n" +
	"\"approved\"H\x01R\x06status\x88\x01\x01\x12]\n" +
	"\bfile_ids\x18\x04 \x01(\v2\x1a.userservice.FileIDsUpdateB!\x92A\x1e2\x1cReplace associated file IDs.H\x02R\afileIds\x88\x01\x01\x12~\n" +
	"\vdescription\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueB9\x92A62\x19New optional description.J\x19\"Adding further details.\"H\x03R\vdescription\x88\x01\x01:\"\x92A\x1f\n" +
	"\x1d*\x16Update Request Request\xd2\x01\x02idB\b\n" +
	"\x06_titleB\t\n" +
	"\a_statusB\v\n" +
	"\t_file_idsB\x0e\n" +
	"\f_description\"g\n" +
	"\x15UpdateRequestResponse\x12.\n" +
	"\arequest\x18\x01 \x01(\v2\x14.userservice.RequestR\arequest:\x1e\x92A\x1b\n" +
	"\x19*\x17Update Request Response\"\xd8\x01\n" +
	"\x14DeleteRequestRequest\x12J\n" +
	"\x02id\x18\x01 \x01(\tB:\x92A72\x1eUUID of the request to delete.J\x15\"request-uuid-string\"R\x02id\x12P\n" +
	"\vhard_delete\x18\x02 \x01(\bB/\x92A,2\x1cPerform hard delete if true.:\x05falseJ\x05falseR\n" +
	"hardDelete:\"\x92A\x1f\n" +
	"\x1d*\x16Delete Request Request\xd2\x01\x02id\"\xc1\x02\n" +
	"\x1cFindByUserParticipantRequest\x12i\n" +
	"\auser_id\x18\x01 \x01(\tBP\x92AM27User ID (UUID) of the participant (sender or receiver).J\x12\"user-uuid-string\"R\x06userId\x12I\n" +
	"\x06status\x18\x02 \x01(\tB,\x92A)2\x1cFilter by status (optional).J\t\"pending\"H\x00R\x06status\x88\x01\x01\x12-\n" +
	"\aoptions\x18\x03 \x01(\v2\x13.core.FilterOptionsR\aoptions:1\x92A.\n" +
	",* Find By User Participant Request\xd2\x01\auser_idB\t\n" +
	"\a_status\"\xba\x01\n" +
	"\x1dFindByUserParticipantResponse\x120\n" +
	"\brequests\x18\x01 \x03(\v2\x14.userservice.RequestR\brequests\x12=\n" +
	"\x0fpagination_info\x18\x02 \x01(\v2\x14.core.PaginationInfoR\x0epaginationInfo:(\x92A%\n" +
	"#*!Find By User Participant Response2\xc2\a\n" +
	"\x0eRequestService\x12\x89\x01\n" +
	"\x06Create\x12!.userservice.CreateRequestRequest\x1a\".userservice.CreateRequestResponse\"8\x92A\x1a\n" +
	"\bRequests\x12\x0eCreate Request\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/requests\x12\x91\x01\n" +
	"\aGetByID\x12\".userservice.GetRequestByIDRequest\x1a#.userservice.GetRequestByIDResponse\"=\x92A\x1d\n" +
	"\bRequests\x12\x11Get Request By ID\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/requests/{id}\x12\x81\x01\n" +
	"\x04List\x12 .userservice.ListRequestsRequest\x1a!.userservice.ListRequestsResponse\"4\x92A\x19\n" +
	"\bRequests\x12\rList Requests\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/requests\x12\x8e\x01\n" +
	"\x06Update\x12!.userservice.UpdateRequestRequest\x1a\".userservice.UpdateRequestResponse\"=\x92A\x1a\n" +
	"\bRequests\x12\x0eUpdate Request\x82\xd3\xe4\x93\x02\x1a:\x01*2\x15/api/v1/requests/{id}\x12\x7f\n" +
	"\x06Delete\x12!.userservice.DeleteRequestRequest\x1a\x16.google.protobuf.Empty\":\x92A\x1a\n" +
	"\bRequests\x12\x0eDelete Request\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/requests/{id}\x12\xcf\x01\n" +
	"\x15FindByUserParticipant\x12).userservice.FindByUserParticipantRequest\x1a*.userservice.FindByUserParticipantResponse\"_\x92A4\n" +
	"\bRequests\n" +
	"\x05Users\x12!Find Requests By User Participant\x82\xd3\xe4\x93\x02\"\x12 /api/v1/users/{user_id}/requests\x1a(\x92A%\x12#Operations related to user requestsB\xa3\x02\x92A\xea\x01\x12`\n" +
	"\x13Request Service API\x12DAPI for managing requests (e.g., leave requests, document requests).2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZL\n" +
	"J\n" +
	"\n" +
	"BearerAuth\x12<\b\x02\x12'JWT Bearer token (e.g., 'Bearer ey...')\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00Z3golang-microservices-boilerplate/proto/user-serviceb\x06proto3"

var (
	file_proto_user_service_request_proto_rawDescOnce sync.Once
	file_proto_user_service_request_proto_rawDescData []byte
)

func file_proto_user_service_request_proto_rawDescGZIP() []byte {
	file_proto_user_service_request_proto_rawDescOnce.Do(func() {
		file_proto_user_service_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_service_request_proto_rawDesc), len(file_proto_user_service_request_proto_rawDesc)))
	})
	return file_proto_user_service_request_proto_rawDescData
}

var file_proto_user_service_request_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_user_service_request_proto_goTypes = []any{
	(*Request)(nil),                       // 0: userservice.Request
	(*CreateRequestRequest)(nil),          // 1: userservice.CreateRequestRequest
	(*CreateRequestResponse)(nil),         // 2: userservice.CreateRequestResponse
	(*GetRequestByIDRequest)(nil),         // 3: userservice.GetRequestByIDRequest
	(*GetRequestByIDResponse)(nil),        // 4: userservice.GetRequestByIDResponse
	(*ListRequestsRequest)(nil),           // 5: userservice.ListRequestsRequest
	(*ListRequestsResponse)(nil),          // 6: userservice.ListRequestsResponse
	(*UpdateRequestRequest)(nil),          // 7: userservice.UpdateRequestRequest
	(*UpdateRequestResponse)(nil),         // 8: userservice.UpdateRequestResponse
	(*DeleteRequestRequest)(nil),          // 9: userservice.DeleteRequestRequest
	(*FindByUserParticipantRequest)(nil),  // 10: userservice.FindByUserParticipantRequest
	(*FindByUserParticipantResponse)(nil), // 11: userservice.FindByUserParticipantResponse
	(*timestamppb.Timestamp)(nil),         // 12: google.protobuf.Timestamp
	(*core.FilterOptions)(nil),            // 13: core.FilterOptions
	(*core.PaginationInfo)(nil),           // 14: core.PaginationInfo
	(*wrapperspb.StringValue)(nil),        // 15: google.protobuf.StringValue
	(*FileIDsUpdate)(nil),                 // 16: userservice.FileIDsUpdate
	(*emptypb.Empty)(nil),                 // 17: google.protobuf.Empty
}
var file_proto_user_service_request_proto_depIdxs = []int32{
	12, // 0: userservice.Request.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: userservice.Request.updated_at:type_name -> google.protobuf.Timestamp
	12, // 2: userservice.Request.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: userservice.CreateRequestResponse.request:type_name -> userservice.Request
	0,  // 4: userservice.GetRequestByIDResponse.request:type_name -> userservice.Request
	13, // 5: userservice.ListRequestsRequest.options:type_name -> core.FilterOptions
	0,  // 6: userservice.ListRequestsResponse.requests:type_name -> userservice.Request
	14, // 7: userservice.ListRequestsResponse.pagination_info:type_name -> core.PaginationInfo
	15, // 8: userservice.UpdateRequestRequest.title:type_name -> google.protobuf.StringValue
	15, // 9: userservice.UpdateRequestRequest.status:type_name -> google.protobuf.StringValue
	16, // 10: userservice.UpdateRequestRequest.file_ids:type_name -> userservice.FileIDsUpdate
	15, // 11: userservice.UpdateRequestRequest.description:type_name -> google.protobuf.StringValue
	0,  // 12: userservice.UpdateRequestResponse.request:type_name -> userservice.Request
	13, // 13: userservice.FindByUserParticipantRequest.options:type_name -> core.FilterOptions
	0,  // 14: userservice.FindByUserParticipantResponse.requests:type_name -> userservice.Request
	14, // 15: userservice.FindByUserParticipantResponse.pagination_info:type_name -> core.PaginationInfo
	1,  // 16: userservice.RequestService.Create:input_type -> userservice.CreateRequestRequest
	3,  // 17: userservice.RequestService.GetByID:input_type -> userservice.GetRequestByIDRequest
	5,  // 18: userservice.RequestService.List:input_type -> userservice.ListRequestsRequest
	7,  // 19: userservice.RequestService.Update:input_type -> userservice.UpdateRequestRequest
	9,  // 20: userservice.RequestService.Delete:input_type -> userservice.DeleteRequestRequest
	10, // 21: userservice.RequestService.FindByUserParticipant:input_type -> userservice.FindByUserParticipantRequest
	2,  // 22: userservice.RequestService.Create:output_type -> userservice.CreateRequestResponse
	4,  // 23: userservice.RequestService.GetByID:output_type -> userservice.GetRequestByIDResponse
	6,  // 24: userservice.RequestService.List:output_type -> userservice.ListRequestsResponse
	8,  // 25: userservice.RequestService.Update:output_type -> userservice.UpdateRequestResponse
	17, // 26: userservice.RequestService.Delete:output_type -> google.protobuf.Empty
	11, // 27: userservice.RequestService.FindByUserParticipant:output_type -> userservice.FindByUserParticipantResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_user_service_request_proto_init() }
func file_proto_user_service_request_proto_init() {
	if File_proto_user_service_request_proto != nil {
		return
	}
	file_proto_user_service_article_proto_init()
	file_proto_user_service_request_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_user_service_request_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_user_service_request_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_service_request_proto_rawDesc), len(file_proto_user_service_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_service_request_proto_goTypes,
		DependencyIndexes: file_proto_user_service_request_proto_depIdxs,
		MessageInfos:      file_proto_user_service_request_proto_msgTypes,
	}.Build()
	File_proto_user_service_request_proto = out.File
	file_proto_user_service_request_proto_goTypes = nil
	file_proto_user_service_request_proto_depIdxs = nil
}
