// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/model-service/model.proto

package modelservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelService_CreateModels_FullMethodName        = "/modelservice.ModelService/CreateModels"
	ModelService_UpdateModels_FullMethodName        = "/modelservice.ModelService/UpdateModels"
	ModelService_DeleteModels_FullMethodName        = "/modelservice.ModelService/DeleteModels"
	ModelService_ListModels_FullMethodName          = "/modelservice.ModelService/ListModels"
	ModelService_ListModelsByStation_FullMethodName = "/modelservice.ModelService/ListModelsByStation"
	ModelService_FindModelByName_FullMethodName     = "/modelservice.ModelService/FindModelByName"
)

// ModelServiceClient is the client API for ModelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelServiceClient interface {
	CreateModels(ctx context.Context, in *CreateModelsRequest, opts ...grpc.CallOption) (*CreateModelsResponse, error)
	UpdateModels(ctx context.Context, in *UpdateModelsRequest, opts ...grpc.CallOption) (*UpdateModelsResponse, error)
	DeleteModels(ctx context.Context, in *DeleteModelsRequest, opts ...grpc.CallOption) (*DeleteModelsResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	ListModelsByStation(ctx context.Context, in *ListModelsByStationRequest, opts ...grpc.CallOption) (*ListModelsByStationResponse, error)
	FindModelByName(ctx context.Context, in *FindModelByNameRequest, opts ...grpc.CallOption) (*FindModelByNameResponse, error)
}

type modelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelServiceClient(cc grpc.ClientConnInterface) ModelServiceClient {
	return &modelServiceClient{cc}
}

func (c *modelServiceClient) CreateModels(ctx context.Context, in *CreateModelsRequest, opts ...grpc.CallOption) (*CreateModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateModelsResponse)
	err := c.cc.Invoke(ctx, ModelService_CreateModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) UpdateModels(ctx context.Context, in *UpdateModelsRequest, opts ...grpc.CallOption) (*UpdateModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateModelsResponse)
	err := c.cc.Invoke(ctx, ModelService_UpdateModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) DeleteModels(ctx context.Context, in *DeleteModelsRequest, opts ...grpc.CallOption) (*DeleteModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteModelsResponse)
	err := c.cc.Invoke(ctx, ModelService_DeleteModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, ModelService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) ListModelsByStation(ctx context.Context, in *ListModelsByStationRequest, opts ...grpc.CallOption) (*ListModelsByStationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsByStationResponse)
	err := c.cc.Invoke(ctx, ModelService_ListModelsByStation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServiceClient) FindModelByName(ctx context.Context, in *FindModelByNameRequest, opts ...grpc.CallOption) (*FindModelByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindModelByNameResponse)
	err := c.cc.Invoke(ctx, ModelService_FindModelByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelServiceServer is the server API for ModelService service.
// All implementations must embed UnimplementedModelServiceServer
// for forward compatibility.
type ModelServiceServer interface {
	CreateModels(context.Context, *CreateModelsRequest) (*CreateModelsResponse, error)
	UpdateModels(context.Context, *UpdateModelsRequest) (*UpdateModelsResponse, error)
	DeleteModels(context.Context, *DeleteModelsRequest) (*DeleteModelsResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	ListModelsByStation(context.Context, *ListModelsByStationRequest) (*ListModelsByStationResponse, error)
	FindModelByName(context.Context, *FindModelByNameRequest) (*FindModelByNameResponse, error)
	mustEmbedUnimplementedModelServiceServer()
}

// UnimplementedModelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelServiceServer struct{}

func (UnimplementedModelServiceServer) CreateModels(context.Context, *CreateModelsRequest) (*CreateModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateModels not implemented")
}
func (UnimplementedModelServiceServer) UpdateModels(context.Context, *UpdateModelsRequest) (*UpdateModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModels not implemented")
}
func (UnimplementedModelServiceServer) DeleteModels(context.Context, *DeleteModelsRequest) (*DeleteModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteModels not implemented")
}
func (UnimplementedModelServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedModelServiceServer) ListModelsByStation(context.Context, *ListModelsByStationRequest) (*ListModelsByStationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModelsByStation not implemented")
}
func (UnimplementedModelServiceServer) FindModelByName(context.Context, *FindModelByNameRequest) (*FindModelByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindModelByName not implemented")
}
func (UnimplementedModelServiceServer) mustEmbedUnimplementedModelServiceServer() {}
func (UnimplementedModelServiceServer) testEmbeddedByValue()                      {}

// UnsafeModelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelServiceServer will
// result in compilation errors.
type UnsafeModelServiceServer interface {
	mustEmbedUnimplementedModelServiceServer()
}

func RegisterModelServiceServer(s grpc.ServiceRegistrar, srv ModelServiceServer) {
	// If the following call pancis, it indicates UnimplementedModelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelService_ServiceDesc, srv)
}

func _ModelService_CreateModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).CreateModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_CreateModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).CreateModels(ctx, req.(*CreateModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_UpdateModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).UpdateModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_UpdateModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).UpdateModels(ctx, req.(*UpdateModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_DeleteModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).DeleteModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_DeleteModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).DeleteModels(ctx, req.(*DeleteModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_ListModelsByStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsByStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).ListModelsByStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_ListModelsByStation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).ListModelsByStation(ctx, req.(*ListModelsByStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelService_FindModelByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindModelByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServiceServer).FindModelByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelService_FindModelByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServiceServer).FindModelByName(ctx, req.(*FindModelByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelService_ServiceDesc is the grpc.ServiceDesc for ModelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "modelservice.ModelService",
	HandlerType: (*ModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateModels",
			Handler:    _ModelService_CreateModels_Handler,
		},
		{
			MethodName: "UpdateModels",
			Handler:    _ModelService_UpdateModels_Handler,
		},
		{
			MethodName: "DeleteModels",
			Handler:    _ModelService_DeleteModels_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _ModelService_ListModels_Handler,
		},
		{
			MethodName: "ListModelsByStation",
			Handler:    _ModelService_ListModelsByStation_Handler,
		},
		{
			MethodName: "FindModelByName",
			Handler:    _ModelService_FindModelByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/model-service/model.proto",
}
