// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/model-service/model.proto

package modelservice

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	core "golang-microservices-boilerplate/proto/core"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	FilePath      string                 `protobuf:"bytes,6,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	TrainedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=trained_at,json=trainedAt,proto3" json:"trained_at,omitempty"`
	StationId     string                 `protobuf:"bytes,10,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	Availability  bool                   `protobuf:"varint,11,opt,name=availability,proto3" json:"availability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_proto_model_service_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_service_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_proto_model_service_model_proto_rawDescGZIP(), []int{0}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Model) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Model) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Model) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Model) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Model) GetTrainedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TrainedAt
	}
	return nil
}

func (x *Model) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *Model) GetAvailability() bool {
	if x != nil {
		return x.Availability
	}
	return false
}

type ModelInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TrainedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=trained_at,json=trainedAt,proto3" json:"trained_at,omitempty"`
	StationId     string                 `protobuf:"bytes,6,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	Availability  bool                   `protobuf:"varint,7,opt,name=availability,proto3" json:"availability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInput) Reset() {
	*x = ModelInput{}
	mi := &file_proto_model_service_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInput) ProtoMessage() {}

func (x *ModelInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_service_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInput.ProtoReflect.Descriptor instead.
func (*ModelInput) Descriptor() ([]byte, []int) {
	return file_proto_model_service_model_proto_rawDescGZIP(), []int{1}
}

func (x *ModelInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInput) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModelInput) GetTrainedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TrainedAt
	}
	return nil
}

func (x *ModelInput) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *ModelInput) GetAvailability() bool {
	if x != nil {
		return x.Availability
	}
	return false
}

type CreateModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInput          `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelsRequest) Reset() {
	*x = CreateModelsRequest{}
	mi := &file_proto_model_service_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelsRequest) ProtoMessage() {}

func (x *CreateModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_service_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelsRequest.ProtoReflect.Descriptor instead.
func (*CreateModelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_service_model_proto_rawDescGZIP(), []int{2}
}

func (x *CreateModelsRequest) GetModels() []*ModelInput {
	if x != nil {
		return x.Models
	}
	return nil
}

type CreateModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModelsResponse) Reset() {
	*x = CreateModelsResponse{}
	mi := &file_proto_model_service_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelsResponse) ProtoMessage() {}

func (x *CreateModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_service_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelsResponse.ProtoReflect.Descriptor instead.
func (*CreateModelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_model_service_model_proto_rawDescGZIP(), []int{3}
}

func (x *CreateModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type UpdateModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModelsRequest) Reset() {
	*x = UpdateModelsRequest{}
	mi := &file_proto_model_service_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelsRequest) ProtoMessage() {}

func (x *UpdateModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_service_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelsRequest.ProtoReflect.Descriptor instead.
func (*UpdateModelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_service_model_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateModelsRequest) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type UpdateModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModelsResponse) Reset() {
	*x = UpdateModelsResponse{}
	mi := &file_proto_model_service_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelsResponse) ProtoMessage() {}

func (x *UpdateModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_service_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelsResponse.ProtoReflect.Descriptor instead.
func (*UpdateModelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_model_service_model_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type DeleteModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	HardDelete    bool                   `protobuf:"varint,2,opt,name=hard_delete,json=hardDelete,proto3" json:"hard_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelsRequest) Reset() {
	*x = DeleteModelsRequest{}
	mi := &file_proto_model_service_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelsRequest) ProtoMessage() {}

func (x *DeleteModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_service_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelsRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_service_model_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteModelsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DeleteModelsRequest) GetHardDelete() bool {
	if x != nil {
		return x.HardDelete
	}
	return false
}

type DeleteModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffectedCount int64                  `protobuf:"varint,1,opt,name=affected_count,json=affectedCount,proto3" json:"affected_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelsResponse) Reset() {
	*x = DeleteModelsResponse{}
	mi := &file_proto_model_service_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelsResponse) ProtoMessage() {}

func (x *DeleteModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_service_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelsResponse.ProtoReflect.Descriptor instead.
func (*DeleteModelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_model_service_model_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteModelsResponse) GetAffectedCount() int64 {
	if x != nil {
		return x.AffectedCount
	}
	return 0
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *core.FilterOptions    `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_proto_model_service_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_service_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_service_model_proto_rawDescGZIP(), []int{8}
}

func (x *ListModelsRequest) GetOptions() *core.FilterOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	Pagination    *core.PaginationInfo   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_proto_model_service_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_service_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_model_service_model_proto_rawDescGZIP(), []int{9}
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResponse) GetPagination() *core.PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListModelsByStationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	Options       *core.FilterOptions    `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsByStationRequest) Reset() {
	*x = ListModelsByStationRequest{}
	mi := &file_proto_model_service_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsByStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsByStationRequest) ProtoMessage() {}

func (x *ListModelsByStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_service_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsByStationRequest.ProtoReflect.Descriptor instead.
func (*ListModelsByStationRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_service_model_proto_rawDescGZIP(), []int{10}
}

func (x *ListModelsByStationRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *ListModelsByStationRequest) GetOptions() *core.FilterOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListModelsByStationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	Pagination    *core.PaginationInfo   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsByStationResponse) Reset() {
	*x = ListModelsByStationResponse{}
	mi := &file_proto_model_service_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsByStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsByStationResponse) ProtoMessage() {}

func (x *ListModelsByStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_service_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsByStationResponse.ProtoReflect.Descriptor instead.
func (*ListModelsByStationResponse) Descriptor() ([]byte, []int) {
	return file_proto_model_service_model_proto_rawDescGZIP(), []int{11}
}

func (x *ListModelsByStationResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsByStationResponse) GetPagination() *core.PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type FindModelByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindModelByNameRequest) Reset() {
	*x = FindModelByNameRequest{}
	mi := &file_proto_model_service_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindModelByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindModelByNameRequest) ProtoMessage() {}

func (x *FindModelByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_service_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindModelByNameRequest.ProtoReflect.Descriptor instead.
func (*FindModelByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_service_model_proto_rawDescGZIP(), []int{12}
}

func (x *FindModelByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FindModelByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindModelByNameResponse) Reset() {
	*x = FindModelByNameResponse{}
	mi := &file_proto_model_service_model_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindModelByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindModelByNameResponse) ProtoMessage() {}

func (x *FindModelByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_service_model_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindModelByNameResponse.ProtoReflect.Descriptor instead.
func (*FindModelByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_model_service_model_proto_rawDescGZIP(), []int{13}
}

func (x *FindModelByNameResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

var File_proto_model_service_model_proto protoreflect.FileDescriptor

const file_proto_model_service_model_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/model-service/model.proto\x12\fmodelservice\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17proto/core/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb9\f\n" +
	"\x05Model\x12{\n" +
	"\x02id\x18\x01 \x01(\tBk\x92Ah2>Unique identifier for the model metadata record (UUID format).J&\"a1b2c3d4-e5f6-7890-1234-567890abcdef\"R\x02id\x12\x8d\x01\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampBR\x92AO25Timestamp when the model metadata record was created.J\x16\"2023-10-27T10:00:00Z\"R\tcreatedAt\x12\x92\x01\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampBW\x92AT2:Timestamp when the model metadata record was last updated.J\x16\"2023-10-27T11:30:00Z\"R\tupdatedAt\x12\xa5\x01\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampBe\x92Ab2HTimestamp when the model metadata was soft-deleted. Null if not deleted.J\x16\"2023-10-28T12:00:00Z\"H\x00R\tdeletedAt\x88\x01\x01\x12J\n" +
	"\x04name\x18\x05 \x01(\tB6\x92A32\x15Name of the AI model.J\x1a\"WaterQualityPredictor_v1\"R\x04name\x12\x82\x01\n" +
	"\tfile_path\x18\x06 \x01(\tBe\x92Ab28Path to the associated model file in the storage system.J&\"/models/WaterQualityPredictor_v1.pkl\"R\bfilePath\x12I\n" +
	"\aversion\x18\a \x01(\tB/\x92A,2!Version identifier for the model.J\a\"1.0.2\"R\aversion\x12\x87\x01\n" +
	"\vdescription\x18\b \x01(\tBe\x92Ab26Description of the model's purpose or characteristics.J(\"Predicts WQI based on sensor readings.\"R\vdescription\x12}\n" +
	"\n" +
	"trained_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampBB\x92A?2%Timestamp when the model was trained.J\x16\"2023-09-15T14:00:00Z\"R\ttrainedAt\x12\x9b\x01\n" +
	"\n" +
	"station_id\x18\n" +
	" \x01(\tB|\x92Ay2OIdentifier (UUID) of the station this model is associated with (if applicable).J&\"b2c3d4e5-f6a7-8901-2345-67890abcdef0\"R\tstationId\x12e\n" +
	"\favailability\x18\v \x01(\bBA\x92A>26Indicates if the model is currently available for use.J\x04trueR\favailability:\xac\x01\x92A\xa8\x01\n" +
	"\xa5\x01*\x11AI Model Metadata2+Represents metadata for a trained AI model.\xd2\x01\x02id\xd2\x01\n" +
	"created_at\xd2\x01\n" +
	"updated_at\xd2\x01\x04name\xd2\x01\tfile_path\xd2\x01\aversion\xd2\x01\n" +
	"trained_at\xd2\x01\n" +
	"station_id\xd2\x01\favailabilityB\r\n" +
	"\v_deleted_at\"\xd4\x06\n" +
	"\n" +
	"ModelInput\x12J\n" +
	"\x04name\x18\x01 \x01(\tB6\x92A32\x15Name of the AI model.J\x1a\"WaterQualityPredictor_v2\"R\x04name\x12I\n" +
	"\aversion\x18\x03 \x01(\tB/\x92A,2!Version identifier for the model.J\a\"2.0.0\"R\aversion\x12\x7f\n" +
	"\vdescription\x18\x04 \x01(\tB]\x92AZ26Description of the model's purpose or characteristics.J \"Improved WQI prediction model.\"R\vdescription\x12}\n" +
	"\n" +
	"trained_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampBB\x92A?2%Timestamp when the model was trained.J\x16\"2024-01-20T10:00:00Z\"R\ttrainedAt\x12\x9b\x01\n" +
	"\n" +
	"station_id\x18\x06 \x01(\tB|\x92Ay2OIdentifier (UUID) of the station this model is associated with (if applicable).J&\"c3d4e5f6-a7b8-9012-3456-7890abcdef01\"R\tstationId\x12w\n" +
	"\favailability\x18\a \x01(\bBS\x92AP2HIndicates if the model should be available for use upon creation/update.J\x04trueR\favailability:\x97\x01\x92A\x93\x01\n" +
	"\x90\x01*\x14Model Input Metadata2>Data required to create or update an AI model metadata record.\xd2\x01\x04name\xd2\x01\aversion\xd2\x01\n" +
	"trained_at\xd2\x01\n" +
	"station_id\xd2\x01\favailability\"\xdc\x01\n" +
	"\x13CreateModelsRequest\x12`\n" +
	"\x06models\x18\x01 \x03(\v2\x18.modelservice.ModelInputB.\x92A+2)List of model metadata details to create.R\x06models:c\x92A`\n" +
	"^*\x15Create Models Request2<Request to create one or more new AI model metadata records.\xd2\x01\x06models\"\xfa\x01\n" +
	"\x14CreateModelsResponse\x12\x80\x01\n" +
	"\x06models\x18\x01 \x03(\v2\x13.modelservice.ModelBS\x92AP2NList of created model metadata records with system-generated fields populated.R\x06models:_\x92A\\\n" +
	"Z*\x16Create Models Response2@Contains details of the newly created AI model metadata records.\"\xfe\x01\n" +
	"\x13UpdateModelsRequest\x12}\n" +
	"\x06models\x18\x01 \x03(\v2\x13.modelservice.ModelBP\x92AM2KList of model metadata with updated fields. Each must include the model ID.R\x06models:h\x92Ae\n" +
	"c*\x15Update Models Request2ARequest to update one or more existing AI model metadata records.\xd2\x01\x06models\"\xcc\x01\n" +
	"\x14UpdateModelsResponse\x12Y\n" +
	"\x06models\x18\x01 \x03(\v2\x13.modelservice.ModelB,\x92A)2'List of updated model metadata records.R\x06models:Y\x92AV\n" +
	"T*\x16Update Models Response2:Contains details of the updated AI model metadata records.\"\xe4\x03\n" +
	"\x13DeleteModelsRequest\x12\x90\x01\n" +
	"\x03ids\x18\x01 \x03(\tB~\x92A{2'List of model metadata UUIDs to delete.JP[\"a1b2c3d4-e5f6-7890-1234-567890abcdef\", \"b2c3d4e5-f6a7-8901-2345-67890abcdef0\"]R\x03ids\x12\xce\x01\n" +
	"\vhard_delete\x18\x02 \x01(\bB\xac\x01\x92A\xa8\x012\x97\x01If true, performs a permanent (hard) delete. If false or omitted, performs a soft delete. Note: Does not delete the associated model file from storage.:\x05falseJ\x05falseR\n" +
	"hardDelete:i\x92Af\n" +
	"d*\x15Delete Models Request2ERequest to delete one or more AI model metadata records by their IDs.\xd2\x01\x03ids\"\xeb\x01\n" +
	"\x14DeleteModelsResponse\x12o\n" +
	"\x0eaffected_count\x18\x01 \x01(\x03BH\x92AE2@Number of model metadata records that were successfully deleted.J\x012R\raffectedCount:b\x92A_\n" +
	"]*\x16Delete Models Response22Contains information about the deletion operation.\xd2\x01\x0eaffected_count\"\xe2\x01\n" +
	"\x11ListModelsRequest\x12_\n" +
	"\aoptions\x18\x01 \x01(\v2\x13.core.FilterOptionsB0\x92A-2+Filtering, pagination, and sorting options.R\aoptions:l\x92Ai\n" +
	"g*\x13List Models Request2PRequest to list AI model metadata records with filtering and pagination options.\"\xeb\x02\n" +
	"\x12ListModelsResponse\x12n\n" +
	"\x06models\x18\x01 \x03(\v2\x13.modelservice.ModelBA\x92A>2<List of model metadata records matching the filter criteria.R\x06models\x12y\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x14.core.PaginationInfoBC\x92A@2>Pagination information including total count and current page.R\n" +
	"pagination:j\x92Ag\n" +
	"e*\x14List Models Response27Contains a paginated list of AI model metadata records.\xd2\x01\x06models\xd2\x01\n" +
	"pagination\"\x92\x03\n" +
	"\x1aListModelsByStationRequest\x12{\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tB\\\x92AY2/UUID of the station to list model metadata for.J&\"b2c3d4e5-f6a7-8901-2345-67890abcdef0\"R\tstationId\x12_\n" +
	"\aoptions\x18\x02 \x01(\v2\x13.core.FilterOptionsB0\x92A-2+Filtering, pagination, and sorting options.R\aoptions:\x95\x01\x92A\x91\x01\n" +
	"\x8e\x01*\x1eList Models By Station Request2_Request to list AI model metadata records for a specific station with filtering and pagination.\xd2\x01\n" +
	"station_id\"\x99\x03\n" +
	"\x1bListModelsByStationResponse\x12n\n" +
	"\x06models\x18\x01 \x03(\v2\x13.modelservice.ModelBA\x92A>2<List of model metadata records matching the filter criteria.R\x06models\x12y\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x14.core.PaginationInfoBC\x92A@2>Pagination information including total count and current page.R\n" +
	"pagination:\x8e\x01\x92A\x8a\x01\n" +
	"\x87\x01*\x1fList Models By Station Response2NContains a paginated list of AI model metadata records for a specific station.\xd2\x01\x06models\xd2\x01\n" +
	"pagination\"\xe7\x01\n" +
	"\x16FindModelByNameRequest\x12Z\n" +
	"\x04name\x18\x01 \x01(\tBF\x92AC2%The unique name of the model to find.J\x1a\"WaterQualityPredictor_v1\"R\x04name:q\x92An\n" +
	"l*\x1aFind Model By Name Request2GRequest to find a specific AI model metadata record by its unique name.\xd2\x01\x04name\"\xe1\x01\n" +
	"\x17FindModelByNameResponse\x12e\n" +
	"\x05model\x18\x01 \x01(\v2\x13.modelservice.ModelB:\x92A725The model metadata record matching the provided name.R\x05model:_\x92A\\\n" +
	"Z*\x1bFind Model By Name Response2;Contains the details of the found AI model metadata record.2\xe3\f\n" +
	"\fModelService\x12\x87\x02\n" +
	"\fCreateModels\x12!.modelservice.CreateModelsRequest\x1a\".modelservice.CreateModelsResponse\"\xaf\x01\x92A\x92\x01\n" +
	"\x06Models\x12\x1dCreate Model Metadata Records\x1aiCreates one or more new AI model metadata records. The associated model file must be uploaded separately.\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/models\x12\xf1\x01\n" +
	"\fUpdateModels\x12!.modelservice.UpdateModelsRequest\x1a\".modelservice.UpdateModelsResponse\"\x99\x01\x92A}\n" +
	"\x06Models\x12\x1dUpdate Model Metadata Records\x1aTUpdates metadata for one or more existing AI models. Does not affect the model file.\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/api/v1/models\x12\xa8\x02\n" +
	"\fDeleteModels\x12!.modelservice.DeleteModelsRequest\x1a\".modelservice.DeleteModelsResponse\"\xd0\x01\x92A\xac\x01\n" +
	"\x06Models\x12\x1dDelete Model Metadata Records\x1a\x82\x01Deletes one or more AI model metadata records. Can be soft or hard delete. Does not delete the associated model file from storage.\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/models/delete\x12\xe1\x01\n" +
	"\n" +
	"ListModels\x12\x1f.modelservice.ListModelsRequest\x1a .modelservice.ListModelsResponse\"\x8f\x01\x92Av\n" +
	"\x06Models\x12\x1bList Model Metadata Records\x1aORetrieves a paginated list of AI model metadata records with filtering options.\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/models\x12\xa2\x02\n" +
	"\x13ListModelsByStation\x12(.modelservice.ListModelsByStationRequest\x1a).modelservice.ListModelsByStationResponse\"\xb5\x01\x92A\x85\x01\n" +
	"\x06Models\x12\x1eList Model Metadata by Station\x1a[Retrieves a paginated list of AI model metadata records associated with a specific station.\x82\xd3\xe4\x93\x02&\x12$/api/v1/stations/{station_id}/models\x12\xe9\x01\n" +
	"\x0fFindModelByName\x12$.modelservice.FindModelByNameRequest\x1a%.modelservice.FindModelByNameResponse\"\x88\x01\x92A`\n" +
	"\x06Models\x12\x1bFind Model Metadata by Name\x1a9Retrieves an AI model metadata record by its unique name.\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/models/by-name/{name}\x1a5\x92A2\x120Operations related to managing AI model metadataB\x80\x02\x92A\xc7\x01\x12=\n" +
	"\x11Model Service API\x12#API for managing AI model metadata.2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZL\n" +
	"J\n" +
	"\n" +
	"BearerAuth\x12<\b\x02\x12'JWT Bearer token (e.g., 'Bearer ey...')\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00Z3golang-microservices-boilerplate/proto/modelserviceb\x06proto3"

var (
	file_proto_model_service_model_proto_rawDescOnce sync.Once
	file_proto_model_service_model_proto_rawDescData []byte
)

func file_proto_model_service_model_proto_rawDescGZIP() []byte {
	file_proto_model_service_model_proto_rawDescOnce.Do(func() {
		file_proto_model_service_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_model_service_model_proto_rawDesc), len(file_proto_model_service_model_proto_rawDesc)))
	})
	return file_proto_model_service_model_proto_rawDescData
}

var file_proto_model_service_model_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_model_service_model_proto_goTypes = []any{
	(*Model)(nil),                       // 0: modelservice.Model
	(*ModelInput)(nil),                  // 1: modelservice.ModelInput
	(*CreateModelsRequest)(nil),         // 2: modelservice.CreateModelsRequest
	(*CreateModelsResponse)(nil),        // 3: modelservice.CreateModelsResponse
	(*UpdateModelsRequest)(nil),         // 4: modelservice.UpdateModelsRequest
	(*UpdateModelsResponse)(nil),        // 5: modelservice.UpdateModelsResponse
	(*DeleteModelsRequest)(nil),         // 6: modelservice.DeleteModelsRequest
	(*DeleteModelsResponse)(nil),        // 7: modelservice.DeleteModelsResponse
	(*ListModelsRequest)(nil),           // 8: modelservice.ListModelsRequest
	(*ListModelsResponse)(nil),          // 9: modelservice.ListModelsResponse
	(*ListModelsByStationRequest)(nil),  // 10: modelservice.ListModelsByStationRequest
	(*ListModelsByStationResponse)(nil), // 11: modelservice.ListModelsByStationResponse
	(*FindModelByNameRequest)(nil),      // 12: modelservice.FindModelByNameRequest
	(*FindModelByNameResponse)(nil),     // 13: modelservice.FindModelByNameResponse
	(*timestamppb.Timestamp)(nil),       // 14: google.protobuf.Timestamp
	(*core.FilterOptions)(nil),          // 15: core.FilterOptions
	(*core.PaginationInfo)(nil),         // 16: core.PaginationInfo
}
var file_proto_model_service_model_proto_depIdxs = []int32{
	14, // 0: modelservice.Model.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: modelservice.Model.updated_at:type_name -> google.protobuf.Timestamp
	14, // 2: modelservice.Model.deleted_at:type_name -> google.protobuf.Timestamp
	14, // 3: modelservice.Model.trained_at:type_name -> google.protobuf.Timestamp
	14, // 4: modelservice.ModelInput.trained_at:type_name -> google.protobuf.Timestamp
	1,  // 5: modelservice.CreateModelsRequest.models:type_name -> modelservice.ModelInput
	0,  // 6: modelservice.CreateModelsResponse.models:type_name -> modelservice.Model
	0,  // 7: modelservice.UpdateModelsRequest.models:type_name -> modelservice.Model
	0,  // 8: modelservice.UpdateModelsResponse.models:type_name -> modelservice.Model
	15, // 9: modelservice.ListModelsRequest.options:type_name -> core.FilterOptions
	0,  // 10: modelservice.ListModelsResponse.models:type_name -> modelservice.Model
	16, // 11: modelservice.ListModelsResponse.pagination:type_name -> core.PaginationInfo
	15, // 12: modelservice.ListModelsByStationRequest.options:type_name -> core.FilterOptions
	0,  // 13: modelservice.ListModelsByStationResponse.models:type_name -> modelservice.Model
	16, // 14: modelservice.ListModelsByStationResponse.pagination:type_name -> core.PaginationInfo
	0,  // 15: modelservice.FindModelByNameResponse.model:type_name -> modelservice.Model
	2,  // 16: modelservice.ModelService.CreateModels:input_type -> modelservice.CreateModelsRequest
	4,  // 17: modelservice.ModelService.UpdateModels:input_type -> modelservice.UpdateModelsRequest
	6,  // 18: modelservice.ModelService.DeleteModels:input_type -> modelservice.DeleteModelsRequest
	8,  // 19: modelservice.ModelService.ListModels:input_type -> modelservice.ListModelsRequest
	10, // 20: modelservice.ModelService.ListModelsByStation:input_type -> modelservice.ListModelsByStationRequest
	12, // 21: modelservice.ModelService.FindModelByName:input_type -> modelservice.FindModelByNameRequest
	3,  // 22: modelservice.ModelService.CreateModels:output_type -> modelservice.CreateModelsResponse
	5,  // 23: modelservice.ModelService.UpdateModels:output_type -> modelservice.UpdateModelsResponse
	7,  // 24: modelservice.ModelService.DeleteModels:output_type -> modelservice.DeleteModelsResponse
	9,  // 25: modelservice.ModelService.ListModels:output_type -> modelservice.ListModelsResponse
	11, // 26: modelservice.ModelService.ListModelsByStation:output_type -> modelservice.ListModelsByStationResponse
	13, // 27: modelservice.ModelService.FindModelByName:output_type -> modelservice.FindModelByNameResponse
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_model_service_model_proto_init() }
func file_proto_model_service_model_proto_init() {
	if File_proto_model_service_model_proto != nil {
		return
	}
	file_proto_model_service_model_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_model_service_model_proto_rawDesc), len(file_proto_model_service_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_model_service_model_proto_goTypes,
		DependencyIndexes: file_proto_model_service_model_proto_depIdxs,
		MessageInfos:      file_proto_model_service_model_proto_msgTypes,
	}.Build()
	File_proto_model_service_model_proto = out.File
	file_proto_model_service_model_proto_goTypes = nil
	file_proto_model_service_model_proto_depIdxs = nil
}
